// angular/src/app/popup/popup.component.ts
import { Component, OnInit, Input } from '@angular/core';

@Component({
  selector: 'app-popup',
  templateUrl: './popup.component.html',
  styleUrls: ['./popup.component.css']
})
export class PopupComponent implements OnInit {
  @Input() show = false;
  @Input() customClass = '';
  @Input() closeCallback = () => (false);

  constructor() { }

  ngOnInit() {
  }

}

<div [ngClass]="customClass || ''" class="popup" [ngStyle]="{display: show ? 'block' : 'none'}">
  <div class="overlay" (click)="closeCallback()"></div>
  <div class="popup_content">
    <ng-content></ng-content>
    <button title="Close" class="close_popup" (click)="closeCallback()">
      <i class="fas fa-times"></i>
    </button>
  </div>
</div>

// react/src/popup/popup.js
import React from 'react';
import PropTypes from 'prop-types';

import './popup.css';

const Popup = ({ children, customClass, show, closeCallback }) => (
  <div className={`popup ${customClass}`} style={{ display: show ? 'block' : 'none'}}>
    <div className="overlay" onClick={closeCallback}></div>
    <div className="popup_content">
      {children}
      <button title="Close" className="close_popup" onClick={closeCallback}>
        <i className="fas fa-times"></i>
      </button>
    </div>
  </div>
);

Popup.propTypes = {
  children: PropTypes.element,
  customClass: PropTypes.string,
  show: PropTypes.bool,
  closeCallback: PropTypes.func,
};

Popup.defaultProps = {
  children: <div>Empty Popup</div>,
  customClass: '',
  show: false,
  closeCallback: () => (false)
};

export default Popup;
